name: ASA Dev Deploy

on:
  push:
    branches:
      - dev
    tags:
      - "asa-app-v*.*.*"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEV_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build ASA image
        run: docker compose -f asa-compose.yml build asa-dev

      - name: Tag ASA image
        env:
          ECR_REPOSITORY: ${{ secrets.ECR_ASA_DEV_REPO }}
        run: |
          docker tag asa-dev:latest $ECR_REPOSITORY:latest

      - name: Push image
        env:
          ECR_REPOSITORY: ${{ secrets.ECR_ASA_DEV_REPO }}
        run: docker push $ECR_REPOSITORY:latest
